const states = [
    { "state_ar": "أدرار", "state_fr": "Adrar", "code": "01", "price": "400" },
    { "state_ar": " الشلف", "state_fr": "Chlef", "code": "02", "price": "200" },
    { "state_ar": "الأغواط", "state_fr": "Laghouat", "code": "03", "price": "" },
    { "state_ar": "أم البواقي", "state_fr": "Oum El Bouaghi", "code": "04", "price": "" },
    { "state_ar": "باتنة", "state_fr": "Batna", "code": "05", "price": "" },
    { "state_ar": " بجاية", "state_fr": "Béjaïa", "code": "06", "price": "" },
    { "state_ar": "بسكرة", "state_fr": "Biskra", "code": "07", "price": "" },
    { "state_ar": "بشار", "state_fr": "Béchar", "code": "08", "price": "" },
    { "state_ar": "البليدة", "state_fr": "Blida", "code": "09", "price": "" },
    { "state_ar": "البويرة", "state_fr": "Bouira", "code": "10", "price": "" },
    { "state_ar": "تمنراست", "state_fr": "Tamanrasset", "code": "11", "price": "" },
    { "state_ar": "تبسة", "state_fr": "Tébessa", "code": "12", "price": "" },
    { "state_ar": "تلمسان", "state_fr": "Tlemcen", "code": "13", "price": "" },
    { "state_ar": "تيارت", "state_fr": "Tiaret", "code": "14", "price": "" },
    { "state_ar": "تيزي وزو", "state_fr": "Tizi Ouzou", "code": "15", "price": "" },
    { "state_ar": "الجزائر", "state_fr": "Alger", "code": "16", "price": "" },
    { "state_ar": "الجلفة", "state_fr": "Djelfa", "code": "17", "price": "" },
    { "state_ar": "جيجل", "state_fr": "Jijel", "code": "18", "price": "" },
    { "state_ar": "سطيف", "state_fr": "Sétif", "code": "19", "price": "" },
    { "state_ar": "سعيدة", "state_fr": "Saïda", "code": "20", "price": "" },
    { "state_ar": "سكيكدة", "state_fr": "Skikda", "code": "21", "price": "" },
    { "state_ar": "سيدي بلعباس", "state_fr": "Sidi Bel Abbès", "code": "22", "price": "" },
    { "state_ar": "عنابة", "state_fr": "Annaba", "code": "23", "price": "" },
    { "state_ar": "قالمة", "state_fr": "Guelma", "code": "24", "price": "" },
    { "state_ar": "قسنطينة", "state_fr": "Constantine", "code": "25", "price": "" },
    { "state_ar": "المدية", "state_fr": "Médéa", "code": "26", "price": "" },
    { "state_ar": "مستغانم", "state_fr": "Mostaganem", "code": "27", "price": "" },
    { "state_ar": "المسيلة", "state_fr": "M'Sila", "code": "28", "price": "" },
    { "state_ar": "معسكر", "state_fr": "Mascara", "code": "29", "price": "" },
    { "state_ar": "ورقلة", "state_fr": "Ouargla", "code": "30", "price": "" },
    { "state_ar": "وهران", "state_fr": "Oran", "code": "31", "price": "" },
    { "state_ar": "البيض", "state_fr": "El Bayadh", "code": "32", "price": "" },
    { "state_ar": "إليزي", "state_fr": "Illizi", "code": "33", "price": "" },
    { "state_ar": "برج بوعريريج", "state_fr": "Bordj Bou Arreridj", "code": "34", "price": "" },
    { "state_ar": "بومرداس", "state_fr": "Boumerdès", "code": "35", "price": "" },
    { "state_ar": "الطارف", "state_fr": "El Tarf", "code": "36", "price": "" },
    { "state_ar": "تندوف", "state_fr": "Tindouf", "code": "37", "price": "" },
    { "state_ar": "تيسمسيلت", "state_fr": "Tissemsilt", "code": "38", "price": "" },
    { "state_ar": "الوادي", "state_fr": "El Oued", "code": "39", "price": "" },
    { "state_ar": "خنشلة", "state_fr": "Khenchela", "code": "40", "price": "" },
    { "state_ar": "سوق أهراس", "state_fr": "Souk Ahras", "code": "41", "price": "" },
    { "state_ar": "تيبازة", "state_fr": "Tipaza", "code": "42", "price": "" },
    { "state_ar": "ميلة", "state_fr": "Mila", "code": "43", "price": "" },
    { "state_ar": "عين الدفلة", "state_fr": "Aïn Defla", "code": "44", "price": "" },
    { "state_ar": "النعامة", "state_fr": "Naâma", "code": "45", "price": "" },
    { "state_ar": "عين تيموشنت", "state_fr": "Aïn Témouchent", "code": "46", "price": "" },
    { "state_ar": "غرداية", "state_fr": "Ghardaïa", "code": "47", "price": "" },
    { "state_ar": "غليزان", "state_fr": "Relizane", "code": "48", "price": "" },
    { "state_ar": "تيميمون", "state_fr": "Timimoun", "code": "49", "price": "" },
    { "state_ar": "برج باجي مختار", "state_fr": "Bordj Badji Mokhtar", "code": "50", "price": "" },
    { "state_ar": "أولاد جلال", "state_fr": "Ouled Djellal", "code": "51", "price": "" },
    { "state_ar": "بني عباس", "state_fr": "Béni Abbès", "code": "52", "price": "" },
    { "state_ar": "عين صالح", "state_fr": "In Salah", "code": "53", "price": "" },
    { "state_ar": "عين قزام", "state_fr": "In Guezzam", "code": "54", "price": "" },
    { "state_ar": "تقرت", "state_fr": "Touggourt", "code": "55", "price": "" },
    { "state_ar": "جانت", "state_fr": "Djanet", "code": "56", "price": "" },
    { "state_ar": "المغير", "state_fr": "El Meghaier", "code": "57", "price": "" },
    { "state_ar": "المنيعة", "state_fr": "El Menia", "code": "58", "price": "" }
  ];
  